name: Codeclimate quality

on:
  push:
    branches:
      - NOTUSE

jobs:
  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Install Dependencies
  #       run: |
  #         npm install
  #         npm install -g yarn
  #         yarn install
  #         yarn build
  #         yarn test

  coverage:
    # needs: [test]
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - run: |
      #     npm install -g yarn
      #     yarn install
      #     yarn build


      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v6.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm run test
          debug: true
