name: Code Coverage

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test & Publish Code Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v6.0.0
        env:
          CC_TEST_REPORTER_ID: <code_climate_reporter_id>
        with:
          coverageCommand: npm run coverage
          debug: true
