name: CodeClimate Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  codeclimate-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install CodeClimate CLI
        run: |
          curl -L https://github.com/codeclimate/codeclimate/archive/master.tar.gz | tar xvz
          sudo mv codeclimate-* /usr/local/bin/codeclimate

      - name: Install dependencies
        run: npm install

      - name: Run CodeClimate analysis
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        run: |
          codeclimate prepare
          codeclimate analyze -f json > codeclimate.json

      - name: Upload report to CodeClimate
        uses: actions/upload-artifact@v2
        with:
          name: codeclimate-report
          path: codeclimate.json
