name: CodeClimate Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
 codeclimate-analysis:
  runs-on: ubuntu-latest
  steps:
  - name: Test & publish code coverage
    uses: paambaati/codeclimate-action@v6.0.0
    env:
      CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
    with:
      coverageCommand: npm run coverage
      debug: true
