name: Codeclimate quality

on:
  pull_request:
    branches:
      - main

jobs:
  codeclimate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests and generate coverage
        run: npm run coverage

      - name: Publish code coverage to Code Climate
        uses: paambaati/codeclimate-action@v6.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm run coverage
          debug: true

      - name: Check score
        run: |
          score=$(curl -s -u "${{ secrets.CC_API_USER }}:${{ secrets.CC_API_TOKEN }}" "https://api.codeclimate.com/v1/repos/${{ secrets.CC_REPO_ID }}/snapshot" | jq -r '.last_snapshot.ratings[0].measure.value')
          min_score=80

          if (( $(echo "$score < $min_score" | bc -l) )); then
            echo "Code Climate score is below minscore: $min_score"
            exit 1
          else
            echo "Code Climate score meets the minimum threshold of $min_score"
          fi
