name: Codeclimate quality

on:
  pull_request:
    branches:
      - main

jobs:
  codeclimate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        
      - name: Install cc-test-reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter

      - name: Run tests and generate coverage
        run: npm run coverage

      - name: List contents of coverage directory
        run: ls -R coverage

      - name: Print coverage report
        run: cat coverage/lcov.info

      - name: Publish code coverage to Code Climate
        run: ./cc-test-reporter format-coverage -t lcov lcov.info && ./cc-test-reporter upload-coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm run coverage
          debug: true

      - name: Check score
        run: |
          score=$(curl -s -u "${{ secrets.CC_API_USER }}:${{ secrets.CC_API_TOKEN }}" "https://api.codeclimate.com/v1/repos/${{ secrets.CC_REPO_ID }}/snapshot" | jq -r '.last_snapshot.ratings[0].measure.value')
          min_score=80

          if (( $(echo "$score < $min_score" | bc -l) )); then
            echo "Code Climate score is below minscore: $min_score"
            exit 1
          else
            echo "Code Climate score meets the minimum threshold of $min_score"
          fi
