name: Code Coverage

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test & Publish Code Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v6.0.0
        env:
          # Set CC_TEST_REPORTER_ID as secret of your repo
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: "${{github.workspace}}/src/main/java"
        with:
          # The report file must be there, otherwise Code Climate won't find it
          coverageCommand: yarn run coverage
          coverageLocations: |
            ${{github.workspace}}/*.lcov:lcov
