name: Jest Testing

on:
  pull_request:
    branches:
      - main

jobs:
  check-test-js:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Check if test.js changes are incremental
      run: |
        if git diff --name-only --diff-filter=AM ${{ github.sha }} HEAD | grep -q __tests__/jest.test.js; then
          echo "test.js has incremental changes"
        else
          echo "test.js does not have incremental changes"
          exit 1
        fi

    - name: Install Dependencies
      run: npm install

    - name: Unit Tests
      run: npm test ./__tests__/jest.test.js
