name: JS Doc Generation
on:
  push:
    branches:
        - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./src/scripts
          output_dir: ./docs

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Commit and push changes
        run: |
          git add ./docs
          git commit -m "Update JS documentation"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}