name: Lighthouse CI
on:
  pull_request:
    branches:
      - main
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install
    - run: npm install -g @lhci/cli@0.13.x
    - run: npm install -g http-server
    - run: http-server -p 8080 &
    - run: sleep 5
    - run: lhci autorun
    #- run: http-server ./src/html/home.html -p 8080 &
    #- run: sleep 5
    #- run: lhci autorun
